### ISSUE TITLE
About MOOS data

### ISSUE THREAD

**Issue by Jason-aplp** [3dlg-hcvc/generalizing_shape_retrieval#1]
Hello,
Thanks for the great work!
But it seems that the url link in the data/moos/download.sh isn't valid?
It says:
wget: missing URL
Usage: wget [OPTION] ... [URL]...
Could u please check the script?
Thanks very much!

**Comment by qiruiw** [comment]
Hi,
Thanks for your interest and pointing out the issue!
We fix the data download links and provide new instructions.
Please refer to the README for the updates :)
