### ISSUE TITLE
Data generation code for MOOS

### ISSUE THREAD

**Issue by DaLi-Jack** [3dlg-hcvc/generalizing_shape_retrieval#2]
Hi! Congratulations on your nice work!
Could you please provide your data generation code for MOOS?
I will be grateful for your help!

**Comment by qiruiw** [comment]
Thanks for your interest!
We briefly describe how to prepare MOOS scenes in the last paragraph of [data part](https://github.com/3dlg-hcvc/generalizing_shape_retrieval?tab=readme-ov-file#data). 
Basically, it only requires to run [this script](https://github.com/3dlg-hcvc/generalizing_shape_retrieval/blob/main/preprocess/moos/render_sample_scene.py).

**Comment by DaLi-Jack** [comment]
Thanks for your prompt and helpful reply!
